version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - AWS_REGION=us-east-2
      - COGNITO_USER_POOL_ID=us-east-2_aCj6mcY5x
      - COGNITO_CLIENT_ID=FashionWizard